import = [
    "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
]

live_config_reload = true

[shell]
# args = ["-l", "-c", "-zellij attach --index 0 --create"]
args = [ "-l", "-c", "zellij attach --index 0 --create" ]

program = "/bin/zsh"

